# Uncomment the next line to define a global platform for your project
platform :ios, '10.12'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

end

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
# pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
# pod 'FirebaseFirestore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :branch => 'master'
pod 'Firebase/Firestore'
