// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl1cCtM6ODsBbqMfMSy-BH64psoPHjR2c',
    appId: '1:903842230586:web:9763870886b40b291ca003',
    messagingSenderId: '903842230586',
    projectId: 'flutter-counter-demo-9209c',
    authDomain: 'flutter-counter-demo-9209c.firebaseapp.com',
    storageBucket: 'flutter-counter-demo-9209c.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC19eOGsANmzf3_c4abE7cerlehg7yRzAQ',
    appId: '1:903842230586:ios:7ac9b223e3f7f34b1ca003',
    messagingSenderId: '903842230586',
    projectId: 'flutter-counter-demo-9209c',
    storageBucket: 'flutter-counter-demo-9209c.appspot.com',
    iosClientId: '903842230586-4kkpfe0ggfgs23q8ect8806lr896a3cm.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
